# Generated by Django 3.2.6 on 2022-03-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostdata',
            name='category',
            field=models.CharField(choices=[('Design & Creative', 'Design & Creative'), ('Design & Development', 'Design & Development'), ('Sales & Marketing', 'Sales & Marketing'), ('Mobile Application', 'Mobile Application'), ('Construction', 'Construction'), ('Information Technology', 'Information Technology'), ('Real Estate', 'Real Estate'), ('Content Writer', 'Content Writer')], default='No category', max_length=50),
        ),
    ]
