# Generated by Django 3.2.6 on 2022-03-12 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostdata',
            old_name='date',
            new_name='posted_date',
        ),
        migrations.AddField(
            model_name='jobpostdata',
            name='application_deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 0, 40, 25, 289233)),
        ),
        migrations.AddField(
            model_name='jobpostdata',
            name='salary',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='jobpostdata',
            name='vacancy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jobpostdata',
            name='category',
            field=models.CharField(choices=[('Design & Creative', 'Design & Creative'), ('Design & Development', 'Design & Development'), ('Sales & Marketing', 'Sales & Marketing'), ('Mobile Application', 'Mobile Application'), ('Construction', 'Construction'), ('Information Technology', 'Information Technology'), ('Real Estate', 'Real Estate'), ('Content Writer', 'Content Writer')], default='No category', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpostdata',
            name='job_nature',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Remote', 'Remote'), ('On site', 'On site')], default='No choice', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobpostdata',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostdata',
            name='title',
            field=models.CharField(default='', max_length=70),
        ),
    ]
