# Generated by Django 3.2.6 on 2022-03-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_jobpostdata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostdata',
            name='job_nature',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Remote', 'Remote'), ('On site', 'On site')], default='No choice', max_length=30),
        ),
    ]
