# Generated by Django 3.2.6 on 2022-03-12 01:13

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_jobpostdata_application_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostdata',
            name='application_deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 1, 13, 51, 382375)),
        ),
        migrations.AlterField(
            model_name='jobpostdata',
            name='desription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
