# Generated by Django 3.2.6 on 2022-03-17 02:13

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220317_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='desription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostdata',
            name='application_deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 2, 13, 11, 561425)),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
