# Generated by Django 3.2.6 on 2022-05-12 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220512_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostdata',
            name='application_deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 6, 6, 39, 551153)),
        ),
    ]
