# Generated by Django 3.2.6 on 2022-05-12 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220512_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
        migrations.AlterField(
            model_name='jobpostdata',
            name='application_deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 10, 45, 7, 812719)),
        ),
    ]
